export const colors = {
  background: '#F2F5FB',
  surface: '#FFFFFF',
  border: '#E4E9F2',
  text: '#0F172A',
  textMuted: '#64748B',
  primary: '#2563EB',
  primaryForeground: '#FFFFFF',
  danger: '#DC2626',
  dangerForeground: '#FFFFFF',
  success: '#16A34A',
  successSurface: '#DCFCE7',
  // Hijau sangat pucat — untuk latar kartu bertema hijau (mis. Kartu Anggota), lebih lembut
  // dari successSurface yang dipakai buat pill/badge.
  successSurfaceSubtle: '#F0FDF7',
  warning: '#F59E0B',
  warningSurface: '#FEF3C7',
  dangerSurface: '#FEE2E2',
  dangerMuted: '#FCA5A5',
  primarySurface: '#DBEAFE',
  neutralSurface: '#F1F5F9',
  gradientEntryStart: '#F59E0B',
  gradientEntryEnd: '#EF4444',
  gradientWeaponStart: '#8B5CF6',
  gradientWeaponEnd: '#4F46E5',
  gradientHealthStart: '#10B981',
  gradientHealthEnd: '#0EA5E9',
  gradientPersonnelStart: '#3B82F6',
  gradientPersonnelEnd: '#2563EB',
  gradientFamilyStart: '#F472B6',
  gradientFamilyEnd: '#EC4899',
  overlay: 'rgba(15, 23, 42, 0.45)',
} as const;
