export const ROUTES = {
  login: 'Login',
  forgotPassword: 'ForgotPassword',
  changePassword: 'ChangePassword',
  main: 'Main',
  home: 'Home',
  riwayat: 'Riwayat',
  emergency: 'Emergency',
  bukuSaku: 'BukuSaku',
  lainnya: 'Lainnya',
  profile: 'Profile',
  catalogList: 'CatalogList',
  catalogDetail: 'CatalogDetail',
  settings: 'Settings',
  comingSoon: 'ComingSoon',
  personnelMap: 'PersonnelMap',
  personnelTracking: 'PersonnelTracking',
  notifications: 'Notifications',
  emergencyList: 'EmergencyList',
  sendAnnouncement: 'SendAnnouncement',
  alarmSatuan: 'AlarmSatuan',
} as const;
