export const ROUTES = {
  login: 'Login',
  forgotPassword: 'ForgotPassword',
  changePassword: 'ChangePassword',
  main: 'Main',
  home: 'Home',
  riwayat: 'Riwayat',
  emergency: 'Emergency',
  bukuSaku: 'BukuSaku',
  profile: 'Profile',
  catalogList: 'CatalogList',
  catalogDetail: 'CatalogDetail',
  settings: 'Settings',
  comingSoon: 'ComingSoon',
  personnelMap: 'PersonnelMap',
} as const;
