export const ROUTES = {
  login: 'Login',
  forgotPassword: 'ForgotPassword',
  changePassword: 'ChangePassword',
  appBootstrap: 'AppBootstrap',
  main: 'Main',
  home: 'Home',
  riwayat: 'Riwayat',
  emergency: 'Emergency',
  bukuSaku: 'BukuSaku',
  bukuSakuDetail: 'BukuSakuDetail',
  academy: 'Academy',
  // Academy = "sub-app" sendiri: tab "Academy" di bar utama push root-stack screen `academyRoot`
  // yang isinya bottom-tab navigator Academy (5 tab di bawah).
  academyRoot: 'AcademyRoot',
  academyBeranda: 'AcademyBeranda',
  academyAkademik: 'AcademyAkademik',
  academyPsikologi: 'AcademyPsikologi',
  academyJasmani: 'AcademyJasmani',
  academyRiwayat: 'AcademyRiwayat',
  // Alur Akademik › TKD (Tes Kompetensi Dasar) — root-stack, di atas AcademyRoot (tanpa bottom tab).
  academyTkdList: 'AcademyTkdList',
  academyTkdModule: 'AcademyTkdModule',
  academyTkdExam: 'AcademyTkdExam',
  academyTkdResult: 'AcademyTkdResult',
  academyTkdReview: 'AcademyTkdReview',
  profile: 'Profile',
  catalogList: 'CatalogList',
  catalogDetail: 'CatalogDetail',
  settings: 'Settings',
  comingSoon: 'ComingSoon',
  personnelMap: 'PersonnelMap',
  personnelTracking: 'PersonnelTracking',
  notifications: 'Notifications',
  emergencyList: 'EmergencyList',
  emergencyDetail: 'EmergencyDetail',
  emergencyContacts: 'EmergencyContacts',
  announcements: 'Announcements',
  myMovements: 'MyMovements',
  meFamilyDetail: 'MeFamilyDetail',
  activityMovements: 'ActivityMovements',
  sendAnnouncement: 'SendAnnouncement',
  alarmSatuan: 'AlarmSatuan',
  healthDashboard: 'HealthDashboard',
  healthPersonnelSearch: 'HealthPersonnelSearch',
  healthPersonnelProfile: 'HealthPersonnelProfile',
  healthRecordInput: 'HealthRecordInput',
  healthRecordDetail: 'HealthRecordDetail',
  healthMyHistory: 'HealthMyHistory',
  rollCallList: 'RollCallList',
  rollCallCreate: 'RollCallCreate',
  rollCallDetail: 'RollCallDetail',
  rollCallSearch: 'RollCallSearch',
  rollCallScan: 'RollCallScan',
  rollCallEntry: 'RollCallEntry',
  // --- Patroli ---
  patrol: 'Patrol',
  patrolRouteDetail: 'PatrolRouteDetail',
  patrolActive: 'PatrolActive',
  patrolScan: 'PatrolScan',
  patrolPhoto: 'PatrolPhoto',
  patrolMonitoring: 'PatrolMonitoring',
  patrolMonitoringDetail: 'PatrolMonitoringDetail',
  // --- Disposisi Surat ---
  dispositionList: 'DispositionList',
  dispositionDetail: 'DispositionDetail',
  dispositionFollowUp: 'DispositionFollowUp',
  dispositionCompose: 'DispositionCompose',
  dispositionRecipientSearch: 'DispositionRecipientSearch',
  incomingLetterList: 'IncomingLetterList',
  incomingLetterCreate: 'IncomingLetterCreate',
  incomingLetterDetail: 'IncomingLetterDetail',
} as const;
